In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import re
import random

In [2]:
PROJECT_ROOT = Path(
    r"D:\dev\projects\fourlang_translation"
)


RAW_DIR = (
    PROJECT_ROOT
    /
    "data"
    /
    "raw"
    /
    "en_uz"
)


CLEAN_DIR = (
    PROJECT_ROOT
    /
    "data"
    /
    "clean"
    /
    "en_uz"
)


EXP2_DIR = (
    CLEAN_DIR
    /
    "exp2"
)


EXP2_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(EXP2_DIR)

D:\dev\projects\fourlang_translation\data\clean\en_uz\exp2

In [3]:
list(
    (CLEAN_DIR/"hplt").iterdir()
)

[WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/directional'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_10k_clean.csv'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_10k_clean.jsonl'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_manual_review_50.csv'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/splits')]

In [4]:
hplt_df = pd.read_csv(
    CLEAN_DIR
    /
    "hplt"
    /
    "hplt_en_uz_10k_clean.csv"
)


print(hplt_df.shape)

hplt_df.head()

(10000, 15)

,pair_id,en,uz,en_sentence_id,uz_sentence_id,src_doc_id,tgt_doc_id,lang_pair,aligner_score,bicleaner_score,bifixer_score,dataset,dataset_revision,en_chars,uz_chars
0,hplt_00000000,"Good place, where you can wait for the, that w...","Yaxshi joy, qaerda kutish mumkin, bu hech qach...",5.9,5.5,http___8cosmos.com_en_moskow__1.xml,http___8cosmos.com_uz_moskow__1.xml,en-uz,0.632494,0.999,0.9159,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,63,59
1,hplt_00000001,- Faculty of Engineering,- Quruvchilik fakulteti,6.1,6.1,http___en.wikipedia.org_wiki_British_Universit...,http___uz.wikipedia.org_wiki_Riga_texnika_univ...,en-uz,0.549205,0.980,0.9502,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,24,23
2,hplt_00000002,- They live mainly in woodland and forest regi...,- Ular asosan o'rmon va o'rmon mintaqalarida i...,7.1,7.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.987,0.9340,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,50,65
3,hplt_00000003,"However, species can be found in desert regions.","Biroq, turlarni cho'l hududlarida topish mumkin.",7.2,7.2,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.999,0.9421,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,48,48
4,hplt_00000004,- They have long tails and slender bodies.,- Ularning uzun quyruqlari va ingichka tanalar...,9.1,9.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.816497,0.994,0.9306,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,42,52

In [6]:
list(
    (CLEAN_DIR/"hplt").iterdir()
)

[WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/directional'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_10k_clean.csv'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_10k_clean.jsonl'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/hplt_en_uz_manual_review_50.csv'),
 WindowsPath('D:/dev/projects/fourlang_translation/data/clean/en_uz/hplt/splits')]

In [7]:
hplt_df = pd.read_csv(
    CLEAN_DIR
    /
    "hplt"
    /
    "hplt_en_uz_10k_clean.csv"
)


print(hplt_df.shape)

hplt_df.head()

(10000, 15)

,pair_id,en,uz,en_sentence_id,uz_sentence_id,src_doc_id,tgt_doc_id,lang_pair,aligner_score,bicleaner_score,bifixer_score,dataset,dataset_revision,en_chars,uz_chars
0,hplt_00000000,"Good place, where you can wait for the, that w...","Yaxshi joy, qaerda kutish mumkin, bu hech qach...",5.9,5.5,http___8cosmos.com_en_moskow__1.xml,http___8cosmos.com_uz_moskow__1.xml,en-uz,0.632494,0.999,0.9159,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,63,59
1,hplt_00000001,- Faculty of Engineering,- Quruvchilik fakulteti,6.1,6.1,http___en.wikipedia.org_wiki_British_Universit...,http___uz.wikipedia.org_wiki_Riga_texnika_univ...,en-uz,0.549205,0.980,0.9502,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,24,23
2,hplt_00000002,- They live mainly in woodland and forest regi...,- Ular asosan o'rmon va o'rmon mintaqalarida i...,7.1,7.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.987,0.9340,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,50,65
3,hplt_00000003,"However, species can be found in desert regions.","Biroq, turlarni cho'l hududlarida topish mumkin.",7.2,7.2,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.999,0.9421,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,48,48
4,hplt_00000004,- They have long tails and slender bodies.,- Ularning uzun quyruqlari va ingichka tanalar...,9.1,9.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.816497,0.994,0.9306,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,42,52

In [8]:
hplt_df = hplt_df.rename(
    columns={
        "en":"src_en",
        "uz":"tgt_uz"
    }
)

In [9]:
hplt_df = hplt_df[
    [
        "src_en",
        "tgt_uz"
    ]
]

In [11]:
tatoeba_df = pd.read_csv(
    CLEAN_DIR
    /
    "tatoeba_en_uz_latin.csv"
)


print(
    tatoeba_df.shape
)


tatoeba_df.head()

(429, 5)

,en_id,en,uz_id,uz,uz_has_cyrillic
0,16996,Mind your own business!,423846,Ishingizni qiling!,False
1,16996,Mind your own business!,423847,Ishingni qil!,False
2,16996,Mind your own business!,423848,Ishinglarni qilinglar!,False
3,19904,The customer did not come.,2790055,Xaridor kelmadi.,False
4,20392,Never mind.,423857,Hech gap yo'q.,False

In [12]:
tatoeba_df = tatoeba_df.rename(
    columns={
        "en":"src_en",
        "uz":"tgt_uz"
    }
)


tatoeba_df = tatoeba_df[
    [
        "src_en",
        "tgt_uz"
    ]
]

In [13]:
opus_df = pd.read_csv(
    RAW_DIR
    /
    "opus"
    /
    "opus100_en_uz.csv"
)


print(
    opus_df.shape
)


opus_df.head()

(173157, 2)

,src_en,tgt_uz
0,Printer '%s' is out of paper.,'%s' printerda qogʻoz tugadi.
1,But surely he who bears patiently and is forgi...,Яхшилар сифати бўлган ушбу сифатларга такрор-т...
2,Intersect Paths,Obʼektlarni guruhlash
3,Lodge them where you lodge according to your m...,"Агар ҳомиладор бўлсалар, то ҳомилаларини қўйгу..."
4,"If He willed, He could still the wind, and the...","Агар У зот хоҳласа, шамолни тўхтатиб қўюр. Бас..."

In [14]:
all_df = pd.concat(
    [
        hplt_df,
        tatoeba_df,
        opus_df
    ],
    ignore_index=True
)


print(
    all_df.shape
)

(183586, 2)

In [15]:
def clean_text(text):

    if pd.isna(text):
        return ""

    text=str(text)

    text=text.strip()

    text=re.sub(
        r"\s+",
        " ",
        text
    )

    return text

In [16]:
all_df["src_en"] = (
    all_df["src_en"]
    .apply(clean_text)
)


all_df["tgt_uz"] = (
    all_df["tgt_uz"]
    .apply(clean_text)
)

In [17]:
all_df = all_df[
    (all_df.src_en!="")
    &
    (all_df.tgt_uz!="")
]


print(
    all_df.shape
)

(183585, 2)

In [18]:
def length_filter(row):

    en_len=len(
        row.src_en.split()
    )

    uz_len=len(
        row.tgt_uz.split()
    )

    return (
        2 <= en_len <= 50
        and
        2 <= uz_len <= 50
    )


all_df = all_df[
    all_df.apply(
        length_filter,
        axis=1
    )
]


print(
    all_df.shape
)

(164924, 2)

In [19]:
all_df = all_df.drop_duplicates(
    subset=[
        "src_en",
        "tgt_uz"
    ]
)


print(
    all_df.shape
)

(146754, 2)

In [21]:
all_df = all_df.drop_duplicates(
    subset=[
        "src_en"
    ]
)


print(
    all_df.shape
)

(142136, 2)

In [22]:
all_df.sample(
    20,
    random_state=42
)

,src_en,tgt_uz
39531,"So oft as they desire to get thereout, they sh...","(Фосиқлар дўзах азобидан қийналиб, ундан қочиб..."
154752,"Woe unto you, for what you describe.","Кўрибсанки, у(ботил) заволга учрабди. Сизларга..."
76155,"Surely, it is in the remembrance of God that h...",Чунки у қалблар ўзларининг Аллоҳга доимий боғл...
33872,Which weighed down your back?,У сенинг елкангни босиб турган эди.
52004,Therefore your Lord struck them hard with the ...,"Бас, Роббинг уларнинг бошига турли азобларни қ..."
40869,"Indeed Allah is all-strong, severe in retribut...","Албатта, Аллоҳ кучли ва иқоби шиддатли зотдир...."
52730,List available sessions,Mavjud boʻlgan profillarni koʻrsatish
65838,And nothing prevents their contributions from ...,Уларнинг нафақаларининг қабул этлишидан ман қи...
62893,"What, and our fathers, the ancients'",Аввалги оталаримиз ҳам-а?!» дер эдилар.
59761,"For them is disgrace in this world, and for th...",Уларга бу дунёда хорлик бордир ва уларга охира...
171625,Thus indeed do We reward the virtuous!,"Албатта, биз гўзал иш қилгувчиларни мана шунда..."
127065,[He is] Knower of the unseen and the witnessed...,"У зот ғойибни ҳам, шоҳидни ҳам билгувчидир. У ..."
156880,"We destroyed people more powerful than they, a...","Бас, Биз улардан кўра кучлироқларни ҳалок қилг..."
26484,"And if you asked them, “Who created the heaven...",Улардан: «Осмонлару ерни ким яратган!» деб сўр...
121639,This is written down in the Eternal Book (of A...,(Xеч бир юрт қолмай азобга ёки ҳалокатга учраш...
75141,So do they not ponder about the Qur’an?,"Агар у Аллоҳдан бошқанинг ҳузуридан бўлганда, ..."
56112,"who spend their property for the cause of God,...","Ва берадиган нарсаларини, албатта, Роббиларига..."
3363,The regenerative braking system can increase t...,Rejenerativ tormoz tizimi oralig'ini 10% ga os...
142597,Had We sent it down upon some non-Arab,Агар Биз уни баъзи ажамийларга нозил қилсак.
146525,We often play chess.,Биз кўпинча шахмат ўйнаймиз.

In [23]:
parallel_df = all_df.sample(
    n=50000,
    random_state=42
)


print(
    parallel_df.shape
)

(50000, 2)

In [24]:
en_uz = pd.DataFrame({

    "src_lang":"en",

    "tgt_lang":"uz",

    "src_text":
        parallel_df["src_en"],

    "tgt_text":
        parallel_df["tgt_uz"]

})

In [25]:
uz_en = pd.DataFrame({

    "src_lang":"uz",

    "tgt_lang":"en",

    "src_text":
        parallel_df["tgt_uz"],

    "tgt_text":
        parallel_df["src_en"]

})

In [26]:
directional_df = pd.concat(
    [
        en_uz,
        uz_en
    ],
    ignore_index=True
)


print(
    directional_df.shape
)

(100000, 4)

In [27]:
directional_df = directional_df.sample(
    frac=1,
    random_state=42
)


train_size=int(
    len(directional_df)*0.9
)


valid_size=int(
    len(directional_df)*0.05
)


train_df = directional_df.iloc[
    :train_size
]


valid_df = directional_df.iloc[
    train_size:
    train_size+valid_size
]


test_df = directional_df.iloc[
    train_size+valid_size:
]


print(
    train_df.shape,
    valid_df.shape,
    test_df.shape
)

(90000, 4) (5000, 4) (5000, 4)

In [28]:
train_df.to_json(
    EXP2_DIR/
    "train_50k.jsonl",

    orient="records",

    lines=True,

    force_ascii=False
)


valid_df.to_json(
    EXP2_DIR/
    "validation.jsonl",

    orient="records",

    lines=True,

    force_ascii=False
)


test_df.to_json(
    EXP2_DIR/
    "test.jsonl",

    orient="records",

    lines=True,

    force_ascii=False
)

In [29]:
print(
    train_df.head()
)

      src_lang tgt_lang                                           src_text  \
75721       uz       en  Улар ўзларига яхшилик етганда: «Бунга биз ҳақд...
80184       uz       en  (Яхшилик етганда ҳаддан ошганидек, ёмонлик етг...
19864       en       uz  And these examples We present to the people th...
76699       uz       en                   Башарият учун огоҳлантирувчидир.
92991       uz       en                                Улар мўмин эмаслар.

                                                tgt_text
75721  Yet when good came their way they said: "It is...
80184  When We grant mercy to the human being, he bec...
19864  Ушбу мисолларни одамларга келтирурмиз, шоядки ...
76699                              A warning to mankind,
92991               For they are not (really) believers.

In [30]:
train_df.groupby(
    [
        "src_lang",
        "tgt_lang"
    ]
).size()

src_lang  tgt_lang
en        uz          44906
uz        en          45094
dtype: int64

In [31]:
print(opus_df.shape)

(173157, 2)

In [32]:
target_opus_num = 50000 - len(hplt_df) - len(tatoeba_df)

print(target_opus_num)

39571

In [33]:
opus_sample_df = opus_df.sample(
    n=target_opus_num,
    random_state=42
)


print(opus_sample_df.shape)

(39571, 2)

In [34]:
all_df = pd.concat(
    [
        hplt_df,
        tatoeba_df,
        opus_sample_df
    ],
    ignore_index=True
)


print(all_df.shape)

(50000, 2)

In [35]:
all_df.sample(
    20,
    random_state=42
)

,src_en,tgt_uz
33553,Local Only,Faqat lokal
9427,Another modification that is frequently seen w...,Tez-tez DHT imkanından bilan qaraladi yana bir...
199,- Disney's Hollywood Studios,"- Disneyʼs Animal Kingdom, 1998-yil 22-aprelda..."
12447,"And I seek refuge with Thee, my Lord! lest the...","Сендан, эй Роббим, уларнинг менга ҳозир бўлишл..."
39489,And We had vouchsafed him of the treasures whe...,"Ўшанда қавми унга: «Ҳовлиқма, албатта, Аллоҳ ҳ..."
42724,God will bring ease after hardship.,"Таоми, кийими ва маскани эрининг зиммасига. Ҳа..."
10822,"And (all) that was their lie, and what they us...",(Аввалги оятларни ўрганиш жараёнида тушунганим...
49498,"But they who disbelieve, and deny Our revelati...",Ва куфр келтирган ҳамда оятларимизни ёлғонга ч...
4144,"But, these factors also adversely reduce the a...","Ammo, bu omillar, shuningdek, ushbu oqsillarni..."
36958,You should most certainly have seen the hell;,"Албатта, жаҳаннамни кўрасизлар."
43106,For He has power over all things.,"Албатта, У зот ҳар бир нарсага қодирдир."
38695,"And it will be judged between them equitably, ...",Улар орасида ҳақ ила ҳукм қилинур ва: «Оламлар...
6188,"Being a broad and interdisciplinary area, Huma...",Insonning biologiyasi keng va fanlararo sohada...
1414,"As I said, we can ignore FLIM FLAM, navneskall...","Aytganimdek, Biz flim FLAM e'tiborsizlik mumki..."
18471,Server URL,Server manzili
29282,Execution,Bajarish
15177,"in honoured scriptures,",Ҳурматланган саҳифалардадир.
34304,Immaculate is He and exalted above [having] an...,У зот улар ширк келтираётган нарсалардан пок в...
12609,Date when file was moved to the Trash,"""%B"" faylini chiqindilar qutisiga olib tashlab..."
12144,"Had your Lord wished, the whole of mankind wou...","Агар Роббинг хоҳласа, ер юзидаги кишиларнинг ҳ..."

In [36]:
import re


def clean_text(text):

    if pd.isna(text):
        return ""

    text=str(text)

    # 去首尾空格
    text=text.strip()

    # 合并连续空格
    text=re.sub(
        r"\s+",
        " ",
        text
    )

    return text

In [37]:
all_df["src_en"] = (
    all_df["src_en"]
    .apply(clean_text)
)


all_df["tgt_uz"] = (
    all_df["tgt_uz"]
    .apply(clean_text)
)

In [38]:
before=len(all_df)


all_df=all_df[
    (all_df.src_en!="")
    &
    (all_df.tgt_uz!="")
]


after=len(all_df)


print(
    "remove:",
    before-after
)

print(
    all_df.shape
)

remove: 0
(50000, 2)

In [50]:
def length_filter(row):

    en_len=len(
        row["src_en"].split()
    )

    uz_len=len(
        row["tgt_uz"].split()
    )


    return (
        2 <= en_len <= 100
        and
        2 <= uz_len <= 100
    )

In [51]:
before=len(all_df)


all_df=all_df[
    all_df.apply(
        length_filter,
        axis=1
    )
]


print(
    "remove:",
    before-len(all_df)
)


print(
    all_df.shape
)

remove: 0
(42384, 2)

In [52]:
before=len(all_df)


all_df=all_df.drop_duplicates(
    subset=[
        "src_en",
        "tgt_uz"
    ]
)


print(
    "remove:",
    before-len(all_df)
)

remove: 0

In [53]:
before=len(all_df)


all_df=all_df.drop_duplicates(
    subset=[
        "src_en"
    ]
)


print(
    "remove:",
    before-len(all_df)
)


print(
    all_df.shape
)

remove: 0
(42384, 2)

In [55]:
print(all_df.shape)

(42384, 2)